Major 03 2022
watson-developer-cloud/java-sdk pull request #1206
Opened 2022-03-18 16:01 UTC by kevinkowa

### Summary

Major release of the SDK Q1

## Assistant V1
### Models
* OutputData: BREAKING required text property removed
* RuntimeEntity: BREAKING optional metadata property removed
* RuntimeResponseGeneric: Three new response types added
* Workspace:  workspaceID changed form required to optional

## Assistant V2
### Models
* MessageContext: integrations property added
* MessageContextGlobalSystem: skipUserInput property added
* MessageContextStateless: integrations property added
* MessageInput: attachments property  added
* MessageInputStateless: attachments property  added
* MessageOutputDebug: BREAKING nodesVisited type DialogNodesVisited changed to DialogNodeVisited. NOTE: The DialogNodesVisited model are deleted
* RuntimeEntity: BREAKING optional metadata property removed
* RuntimeResponseGeneric: Three new response types added

## Discovery V1
### Models
* DocumentStatus: documentID, status, and statusDescription are now optional
* QueryAggregation: BREAKING QueryAggregation subclasses changed. Old models are deleted!
* 
## CC
* Removed

## LT
* Updated unit tests

## NLC
* Removed

## NLU
* Updated unit tests and comments

## PI
* Removed

## STT
### Models
* SupportedFeatures: customAcousticModel property added

## TTS
* Nothing

## Tone Analyzer
* Removed

## VisualRecognition
* Removed

2022-03-18 19:29 UTC, apaparazzi0329 requested changes
LGTM

2022-03-18 19:29 UTC, apaparazzi0329 commented on examples/src/main/java/com/ibm/watson/assistant/v1/tone_analyzer_integration/AssistantToneAnalyzerIntegrationExample.java
> - * (C) Copyright IBM Corp. 2019, 2020.
This file should be deleted

2022-03-18 19:29 UTC, apaparazzi0329 commented on examples/src/main/java/com/ibm/watson/assistant/v1/tone_analyzer_integration/ToneDetection.java
> - * (C) Copyright IBM Corp. 2018, 2020.
File should be deleted

2022-03-21 15:14 UTC, Hsaylor approved these changes
straight up this PR is lagging chrome

2022-03-21 15:32 UTC, repjarms approved these changes

2022-03-21 16:57 UTC, merged