Release q3 2022
watson-developer-cloud/java-sdk pull request #1211
Opened 2022-08-08 20:35 UTC by apaparazzi0329

Assistant V1
### Models
* RuntimeIntent: `confidence` is no longer a required parameter
* Workspace: New status available: “processing”, new properties added: `statusErrors` and `counts`
* WorkspaceSystemSettings: New property `nlp`

### Methods
* NEW Method: `createWorkspaceAsync`
* NEW Method: `updateWorkspaceAsync`
* NEW Method: `exportWorkspaceAsync`

## Assistant V2
### Models
* BulkClassifyOptions: add `input` as required property
* MessageOutputDebug: add `turnEvents` property
* RuntimeEntity: add `skill` property
* RuntimeIntent: add `skill` property and `confidence` no longer a required property
* RuntimeResponseGeneric: Date type added

### Methods
* NEW Method: `listEnvironments`
* NEW Method: `getEnvironments`
* NEW Method: `listReleases`
* NEW Method: `getRelease`
* NEW Method: `deployRelease`

## Discovery V1
* No changes

## Discovery V2
### Models
* add parameter  `smartDocumentUnderstanding` to `createCollection`  and `updateCollection`
* Enrichment: new type `clarifier`
* add parameters `classifierId`, `modelId`, `confidenceThreshold`, `topK` to `createEnrichment` and `updateEnrichment`
* add parameter `similar` to `query`

### Methods
* NEW Method: `listDocuments`
* NEW Method: `getDocument`
* NEW Method: `listDocumentClassifiers`
* NEW Method: `createDocumentClassifier`
* NEW Method: `getDocumentClassifier`
* NEW Method: `updateDocumentClassifier`
* NEW Method: `deleteDocumentClassifier`
* NEW Method: `listDocumentClassifierModels`
* NEW Method: `createDocumentClassifierModel`
* NEW Method: `getDocumentClassifierModel`
* NEW Method: `updateDocumentClassifierModel`
* NEW Method: `deleteDocumentClassifierModel`
* NEW Method: `getStopwordList`
* NEW Method: `createStopwordList`
* NEW Method: `deleteStopwordList`
* NEW Method: `listExpansions`
* NEW Method: `createExpansions`
* NEW Method: `deleteExpansions`

## LT
* Nothing

## NLU
### Models
* add parameter `trainingParameters` to `createClassificationsModel` and `updateClassificationsModel`

## STT
### Models
* Remove parameter `customizationId`  from  `createJob` and `recognize`
* Add parameter `characterInsertionBias` to `createJob` and `recognize`
* Add parameter `strict` to `trainAcousticModel` and `trainLanguageModel`

## TTS
### Models
* Add parameter  `spellOutMode` to `synthesize`

2022-08-09 16:17 UTC, kevinkowa requested changes
Make sure you run detect-secrets

2022-08-09 17:16 UTC, apaparazzi0329 commented
Done

2022-08-09 21:23 UTC, kevinkowa commented on assistant/src/main/java/com/ibm/watson/assistant/v1/model/DialogNodeOutputGenericDialogNodeOutputResponseTypeAudio.java
> +  protected DialogNodeOutputGenericDialogNodeOutputResponseTypeAudio() {}
I see that this type of empty protected class is happening everywhere, I think that's part of the new version for the generator

2022-08-09 21:37 UTC, kevinkowa approved these changes
Looks good to me 👍 🥇

2022-08-10 16:34 UTC, kevinkowa approved these changes
LGTM!
![](https://media.giphy.com/media/lYpOXbTyaTF60/giphy.gif)

2022-08-10 16:38 UTC, merged